# Copyright (C) 2022, Gauthier Leonard
# See the file LICENSE for licensing terms.
---
- name: "Create {{ avalanchego_user }} user"
  user:
    name: "{{ avalanchego_user }}"

- name: Create AvalancheGo dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ avalanchego_user }}"
    group: "{{ avalanchego_user }}"
  loop:
    - "{{ avalanchego_plugins_dir }}"
    - "{{ avalanchego_releases_dir }}"
    - "{{ avalanchego_db_dir }}"
    - "{{ avalanchego_chains_conf_dir }}"
    - "{{ avalanchego_vms_conf_dir }}"
    - "{{ avalanchego_certs_dir }}"
    - "{{ avalanchego_log_dir }}"

- name: Bootstrap database
  include_tasks: bootstrap-db.yml
  when: (avalanchego_bootstrap_db is defined) and (avalanchego_bootstrap_db|length > 0)

- name: Download AvalancheGo binary
  get_url:
    url: "{{ avalanchego_binary_url }}"
    dest: "{{ avalanchego_releases_dir }}/{{ avalanchego_binary_name }}"
    owner: "{{ avalanchego_user }}"
    group: "{{ avalanchego_user }}"

- name: Unpack AvalancheGo binary
  unarchive:
    src: "{{ avalanchego_releases_dir }}/{{ avalanchego_binary_name }}"
    dest: "{{ avalanchego_install_dir }}"
    owner: "{{ avalanchego_user }}"
    group: "{{ avalanchego_user }}"
    remote_src: yes
    creates: "{{ avalanchego_install_dir }}/avalanchego-v{{ avalanchego_version }}"

- name: Create the symlink to current AvalancheGo binary
  file:
    src: "{{ avalanchego_install_dir }}/avalanchego-v{{ avalanchego_version }}/avalanchego"
    dest: "{{ avalanchego_current_dir }}/avalanchego"
    state: link
    owner: "{{ avalanchego_user }}"
    group: "{{ avalanchego_user }}"
  notify: Restart avalanchego

- name: Create the symlink to current evm binary in plugins dir
  file:
    src: "{{ avalanchego_install_dir }}/avalanchego-v{{ avalanchego_version }}/plugins/evm"
    dest: "{{ avalanchego_plugins_dir }}/evm"
    state: link
    owner: "{{ avalanchego_user }}"
    group: "{{ avalanchego_user }}"
  notify: Restart avalanchego

- name: Template avalanchego.service file
  template:
    src: avalanchego.service.j2
    dest: /etc/systemd/system/avalanchego.service
  notify: Restart avalanchego

- name: Reload systemctl daemons
  systemd:
    daemon_reload: yes
