# Copyright (C) 2022, Gauthier Leonard
# See the file LICENSE for licensing terms.
---
- name: Install AvalancheGo
  include_tasks: install-avalanchego.yml

- name: Install VMs
  include_tasks: install-vm.yml
  vars:
    vm_name: "{{ vm.split('=')[0] }}"
    vm_version: "{{ vm.split('=')[1] }}"
    vm_info: "{{ avalanchego_vms_list[vm.split('=')[0]] }}"
  loop: "{{ avalanchego_vms_install }}"
  loop_control:
    loop_var: vm

- name: Configure AvalancheGo node
  include_tasks: config-node.yml

- name: Configure chains
  include_tasks: config-chains.yml

- name: Start AvalancheGo node
  include_tasks: start.yml
