# Copyright (C) 2022, Gauthier Leonard
# See the file LICENSE for licensing terms.
---
- name: Restart AvalancheGo and reload VMs if needed
  meta: flush_handlers

- name: Start and enable avalanchego.service
  service:
    name: avalanchego
    state: started
    enabled: yes
